server:
  port: 80

spring:
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  application:
    name: cloud-order-service

eureka:
  instance:
    hostname: localhost
    instance-id: order80
    #发送心跳的时间
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/
