spring:
  application:
    name: Service


server:
  port: 7001


eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000

  instance:
    hostname: eureka01

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/



