server:
  port: 8003

spring:
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  application:
    name: cloud-payment-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.199.10:3306/payment?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456





mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yangtengfei.springcloud.entities
