server:
  port: 8002

spring:
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.199.242:3306/payment?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456

eureka:
  instance:
    hostname: localhost
    instance-id: payment8002

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yangtengfei.springcloud.entities
